"""add_gym_schedule_slots_and_equipment_fields

Revision ID: 852fa786cde3
Revises: bf7896e5841g
Create Date: 2025-12-10 23:15:46.543257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '852fa786cde3'
down_revision: Union[str, Sequence[str], None] = 'bf7896e5841g'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gym_schedule_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.String(length=20), nullable=False),
    sa.Column('end_time', sa.String(length=20), nullable=False),
    sa.Column('slot_type', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trainer_id', sa.UUID(), nullable=True),
    sa.Column('max_capacity', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gym_schedule_slots_id'), 'gym_schedule_slots', ['id'], unique=False)
    op.add_column('equipment', sa.Column('maintenance_notes', sa.Text(), nullable=True))
    op.add_column('equipment', sa.Column('serial_number', sa.String(length=100), nullable=True))
    op.add_column('equipment', sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('equipment', sa.Column('warranty_expiry', sa.DateTime(timezone=True), nullable=True))
    op.add_column('trainer_documents', sa.Column('document_type', sa.String(length=50), nullable=False))
    op.alter_column('trainer_documents', 'trainer_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('trainer_leaves', 'trainer_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trainer_leaves', 'trainer_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('trainer_documents', 'trainer_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_column('trainer_documents', 'document_type')
    op.drop_column('equipment', 'warranty_expiry')
    op.drop_column('equipment', 'purchase_date')
    op.drop_column('equipment', 'serial_number')
    op.drop_column('equipment', 'maintenance_notes')
    op.drop_index(op.f('ix_gym_schedule_slots_id'), table_name='gym_schedule_slots')
    op.drop_table('gym_schedule_slots')
    # ### end Alembic commands ###
