"""Add new trainer fields

Revision ID: af4595e4740f
Revises: 
Create Date: 2025-12-08 19:10:05.965900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af4595e4740f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('paid_to', sa.String(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('bill_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pt_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sessions_count', sa.Integer(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('includes_diet_plan', sa.Boolean(), nullable=True),
    sa.Column('includes_supplements', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_otp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('otp', sa.String(length=6), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('login_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_activity', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('requires_2fa', sa.Boolean(), nullable=True),
    sa.Column('two_factor_verified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_sessions_id'), 'admin_sessions', ['id'], unique=False)
    op.create_table('progress_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trainee_id', sa.Integer(), nullable=False),
    sa.Column('photo_type', sa.String(length=50), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('date_taken', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['trainee_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_photos_id'), 'progress_photos', ['id'], unique=False)
    op.create_table('pt_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.UUID(), nullable=False),
    sa.Column('trainee_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('session_date', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('exercises_done', sa.Text(), nullable=True),
    sa.Column('trainer_notes', sa.Text(), nullable=True),
    sa.Column('trainee_feedback', sa.Text(), nullable=True),
    sa.Column('calories_burned', sa.Integer(), nullable=True),
    sa.Column('performance_rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['pt_packages.id'], ),
    sa.ForeignKeyConstraint(['trainee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trainer_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('check_in', sa.DateTime(), nullable=True),
    sa.Column('check_out', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('hours_worked', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('leave_reason', sa.String(length=200), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trainer_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.Column('document_name', sa.String(length=200), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trainer_leaves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.Column('leave_type', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trainer_salaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.UUID(), nullable=False),
    sa.Column('salary_model', sa.String(length=20), nullable=True),
    sa.Column('base_salary', sa.Float(), nullable=True),
    sa.Column('commission_per_trainee', sa.Float(), nullable=True),
    sa.Column('commission_per_session', sa.Float(), nullable=True),
    sa.Column('monthly_bonus', sa.Float(), nullable=True),
    sa.Column('performance_bonus', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trainer_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('specific_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_reports_id'), 'ai_reports', ['id'], unique=False)
    op.drop_constraint(op.f('ai_reports_trainee_id_fkey'), 'ai_reports', type_='foreignkey')
    op.create_foreign_key(None, 'ai_reports', 'trainees', ['trainee_id'], ['id'])
    op.create_index(op.f('ix_attendance_id'), 'attendance', ['id'], unique=False)
    op.create_index(op.f('ix_diet_plans_id'), 'diet_plans', ['id'], unique=False)
    op.create_index(op.f('ix_equipment_id'), 'equipment', ['id'], unique=False)
    op.create_index(op.f('ix_measurements_id'), 'measurements', ['id'], unique=False)
    op.create_index(op.f('ix_membership_plans_id'), 'membership_plans', ['id'], unique=False)
    op.create_index(op.f('ix_memberships_id'), 'memberships', ['id'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_nutrition_logs_id'), 'nutrition_logs', ['id'], unique=False)
    op.add_column('payments', sa.Column('receipt_number', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('payment_mode', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('receipt_pdf_url', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('is_refund', sa.Boolean(), nullable=True))
    op.add_column('payments', sa.Column('refund_amount', sa.Float(), nullable=True))
    op.add_column('payments', sa.Column('refund_reason', sa.String(), nullable=True))
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_receipt_number'), 'payments', ['receipt_number'], unique=True)
    op.alter_column('progress_measurements', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_progress_measurements_id'), 'progress_measurements', ['id'], unique=False)
    op.drop_constraint(op.f('trainees_user_id_fkey'), 'trainees', type_='foreignkey')
    op.create_foreign_key(None, 'trainees', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_trainer_messages_id'), 'trainer_messages', ['id'], unique=False)
    op.alter_column('trainer_revenue', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_trainer_revenue_id'), 'trainer_revenue', ['id'], unique=False)
    op.add_column('trainers', sa.Column('aadhar_number', sa.String(length=20), nullable=True))
    op.add_column('trainers', sa.Column('pan_number', sa.String(length=20), nullable=True))
    op.add_column('trainers', sa.Column('emergency_contact_name', sa.String(length=100), nullable=True))
    op.add_column('trainers', sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True))
    op.add_column('trainers', sa.Column('blood_group', sa.String(length=10), nullable=True))
    op.add_column('trainers', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('trainers', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('trainers', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('trainers', sa.Column('pincode', sa.String(length=10), nullable=True))
    op.add_column('trainers', sa.Column('bank_account_number', sa.String(length=50), nullable=True))
    op.add_column('trainers', sa.Column('ifsc_code', sa.String(length=20), nullable=True))
    op.add_column('trainers', sa.Column('bank_name', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'trainers', ['pan_number'])
    op.create_unique_constraint(None, 'trainers', ['aadhar_number'])
    op.drop_constraint(op.f('trainers_user_id_fkey'), 'trainers', type_='foreignkey')
    op.create_foreign_key(None, 'trainers', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_constraint(op.f('workouts_trainee_id_fkey'), 'workouts', type_='foreignkey')
    op.create_foreign_key(None, 'workouts', 'users', ['trainee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workouts', type_='foreignkey')
    op.create_foreign_key(op.f('workouts_trainee_id_fkey'), 'workouts', 'users', ['trainee_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'trainers', type_='foreignkey')
    op.create_foreign_key(op.f('trainers_user_id_fkey'), 'trainers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'trainers', type_='unique')
    op.drop_constraint(None, 'trainers', type_='unique')
    op.drop_column('trainers', 'bank_name')
    op.drop_column('trainers', 'ifsc_code')
    op.drop_column('trainers', 'bank_account_number')
    op.drop_column('trainers', 'pincode')
    op.drop_column('trainers', 'state')
    op.drop_column('trainers', 'city')
    op.drop_column('trainers', 'address')
    op.drop_column('trainers', 'blood_group')
    op.drop_column('trainers', 'emergency_contact_phone')
    op.drop_column('trainers', 'emergency_contact_name')
    op.drop_column('trainers', 'pan_number')
    op.drop_column('trainers', 'aadhar_number')
    op.drop_index(op.f('ix_trainer_revenue_id'), table_name='trainer_revenue')
    op.alter_column('trainer_revenue', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_trainer_messages_id'), table_name='trainer_messages')
    op.drop_constraint(None, 'trainees', type_='foreignkey')
    op.create_foreign_key(op.f('trainees_user_id_fkey'), 'trainees', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_progress_measurements_id'), table_name='progress_measurements')
    op.alter_column('progress_measurements', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_payments_receipt_number'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_column('payments', 'refund_reason')
    op.drop_column('payments', 'refund_amount')
    op.drop_column('payments', 'is_refund')
    op.drop_column('payments', 'notes')
    op.drop_column('payments', 'receipt_pdf_url')
    op.drop_column('payments', 'payment_mode')
    op.drop_column('payments', 'receipt_number')
    op.drop_index(op.f('ix_nutrition_logs_id'), table_name='nutrition_logs')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_memberships_id'), table_name='memberships')
    op.drop_index(op.f('ix_membership_plans_id'), table_name='membership_plans')
    op.drop_index(op.f('ix_measurements_id'), table_name='measurements')
    op.drop_index(op.f('ix_equipment_id'), table_name='equipment')
    op.drop_index(op.f('ix_diet_plans_id'), table_name='diet_plans')
    op.drop_index(op.f('ix_attendance_id'), table_name='attendance')
    op.drop_constraint(None, 'ai_reports', type_='foreignkey')
    op.create_foreign_key(op.f('ai_reports_trainee_id_fkey'), 'ai_reports', 'trainees', ['trainee_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_ai_reports_id'), table_name='ai_reports')
    op.drop_table('trainer_schedules')
    op.drop_table('trainer_salaries')
    op.drop_table('trainer_leaves')
    op.drop_table('trainer_documents')
    op.drop_table('trainer_attendance')
    op.drop_table('pt_sessions')
    op.drop_index(op.f('ix_progress_photos_id'), table_name='progress_photos')
    op.drop_table('progress_photos')
    op.drop_index(op.f('ix_admin_sessions_id'), table_name='admin_sessions')
    op.drop_table('admin_sessions')
    op.drop_table('admin_otp')
    op.drop_table('pt_packages')
    op.drop_table('expenses')
    # ### end Alembic commands ###
    
    
    