"""Add admin settings fields

Revision ID: fac9e4c4578a
Revises: 3d74f32ad8c0
Create Date: 2025-12-24 19:14:51.070340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fac9e4c4578a'
down_revision: Union[str, Sequence[str], None] = '3d74f32ad8c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_settings', sa.Column('gym_name', sa.String(length=255), nullable=True))
    op.add_column('admin_settings', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('admin_settings', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('admin_settings', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('admin_settings', sa.Column('timezone', sa.String(length=50), nullable=True))
    op.add_column('admin_settings', sa.Column('currency', sa.String(length=10), nullable=True))
    op.add_column('admin_settings', sa.Column('email_notifications', sa.Boolean(), nullable=True))
    op.add_column('admin_settings', sa.Column('maintenance_reminders', sa.Boolean(), nullable=True))
    op.add_column('admin_settings', sa.Column('schedule_notifications', sa.Boolean(), nullable=True))
    op.add_column('admin_settings', sa.Column('max_failed_logins', sa.Integer(), nullable=True))
    op.add_column('admin_settings', sa.Column('session_timeout_minutes', sa.Integer(), nullable=True))
    op.add_column('admin_settings', sa.Column('backup_enabled', sa.Boolean(), nullable=True))
    op.add_column('admin_settings', sa.Column('auto_backup_enabled', sa.Boolean(), nullable=True))
    op.add_column('admin_settings', sa.Column('backup_frequency', sa.String(length=20), nullable=True))
    op.add_column('admin_settings', sa.Column('data_retention_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_settings', 'data_retention_days')
    op.drop_column('admin_settings', 'backup_frequency')
    op.drop_column('admin_settings', 'auto_backup_enabled')
    op.drop_column('admin_settings', 'backup_enabled')
    op.drop_column('admin_settings', 'session_timeout_minutes')
    op.drop_column('admin_settings', 'max_failed_logins')
    op.drop_column('admin_settings', 'schedule_notifications')
    op.drop_column('admin_settings', 'maintenance_reminders')
    op.drop_column('admin_settings', 'email_notifications')
    op.drop_column('admin_settings', 'currency')
    op.drop_column('admin_settings', 'timezone')
    op.drop_column('admin_settings', 'address')
    op.drop_column('admin_settings', 'phone')
    op.drop_column('admin_settings', 'email')
    op.drop_column('admin_settings', 'gym_name')
    # ### end Alembic commands ###
